export declare function patchGlobalThis(): typeof globalThis;
export declare const _Sym: SymbolConstructor;
export declare const has: (a: string | number | symbol, b: object) => boolean;
export declare const emptyObj: {};
export declare const emptyArr: never[];
export declare const isIterable: (k: any) => any;
export declare const _Object: ObjectConstructor;
export declare const hasOwnProp: (v: PropertyKey) => boolean;
export declare function _generateDocFrag(args: (Node | (string | number | boolean | symbol))[]): DocumentFragment;
export declare const domContext: boolean;
export declare const workerContext: boolean;
export declare const isBrowser: boolean;
