"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const util_js_1 = require("../../util.js");
let _global = util_js_1.patchGlobalThis();
exports.HAS_MAP = util_js_1.has("Map", _global);
exports.HAS_SET = util_js_1.has("Set", _global);
exports.HAS_WEAK = util_js_1.has("WeakMap", _global) && util_js_1.has("WeakSet", _global);
exports.m = "__@@map";
exports.s = "__@@set";
const _isNaN = (k) => k !== k;
exports._EqCheck = (x, y) => x === y || (_isNaN(x) && _isNaN(y));
exports.normalizeNegativeZero = (k) => (k === 0 ? 0 : k);
exports._mapKey = "__@@mkey";
exports._mapVal = "__@mVal";
