"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var index_js_1 = require("./Map/index.js");
exports.FakeMap = index_js_1.default;
var index_js_2 = require("./Set/index.js");
exports.FakeSet = index_js_2.default;
var index_js_3 = require("./WeakMap/index.js");
exports.FakeWeakMap = index_js_3.default;
exports.patchObjectSealingMethods = index_js_3.patchObjectSealingMethods;
var index_js_4 = require("./WeakSet/index.js");
exports.FakeWeakSet = index_js_4.default;
