"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var assign_js_1 = require("./assign.js");
exports.Object_assign = assign_js_1.default;
var keys_js_1 = require("./keys.js");
exports.Object_keys = keys_js_1.default;
var entries_js_1 = require("./entries.js");
exports.Object_entries = entries_js_1.default;
var values_js_1 = require("./values.js");
exports.Object_values = values_js_1.default;
var fromEntries_js_1 = require("./fromEntries.js");
exports.Object_fromEntries = fromEntries_js_1.default;
var is_js_1 = require("./is.js");
exports.Object_is = is_js_1.default;
